services:
  cliente:
    container_name: asir_cliente
    image: alpine
    platform: linux/amd64
    tty: true
    stdin_open: true
    networks:
      - bind9_subnet
networks:
  bind9_subnet:
    external: true