services:
  asir_bind9:
    container_name: asir_bind9
    image: ubuntu/bind9
    # usamos esta imagen para ver los logs
    # la imagen internetconsortium no muestra logs
    platform: linux/amd64
    ports:
      - 53:53
      #Mapeo de puertos
    networks:
    #Creamos la red y le damos ip al DNS
      bind9_subnet:
        ipv4_address: 172.28.5.1
    volumes:
    #Volumenes
      - ./config:/etc/bind
      - ./lib:/var/lib/bind
      - ./logs:/var/log/bind
networks:
  bind9_subnet:
    external: true